server:
  port: 8080   #当前应用运行端口号
spring:
  mvc:
    static-path-pattern=/static/**:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

