server:
  port: 8080

  datasource:
    url: jdbc:mysql://localhost:3306/aaa?useUnicode=true&characterEncoding=utf8
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver

